# version: '3.8'
# services:
#   nginx:
#     container_name: my-nginx-container
#     image: nginx:latest
#     ports:
#       - 80:80
#     volumes:
#       - ./my-nginx-html-volumn/:/usr/share/nginx/html/
#       # - ./nginx.conf:/etc/nginx/nginx.conf

version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nginx-container
    ports:
      - 80:80
    volumes:
      - ./my-nginx-html-volumn/:/usr/share/nginx/html/
      # - ./nginx.conf:/etc/nginx/nginx.conf

